### ISSUE TITLE
False negative error shown for methods with multidimensional array return types

### ISSUE THREAD

**Issue by DirajHS** [tikurahul/baseline-profiles-idea-plugin#1]
Great work on the plugin!!
While integrating baseline profiles in our app, we noticed some of the methods having multidimensional array as return types and there corresponding profile entries looks like:
```
HSPLcom/turbo/internal/setChildId;->getBody(I)[[B
```
and  the method signature itself looks like:
```java
byte[][] com.turbo.internal.setChildId.getBody(int)
```
This plugin(v 0.1.6) currently reports the multiple `[` (square brackets at the end) as an error which seems to be incorrect as the profile generated is successfully compiled. Syntax highlighting stops after flagging this as an error as well. 

Error message shown: `<primitives>, L or NEWLINE expected, got '['`

### Steps to reproduce 
* Add the profile entry similar to the one mentioned above in any existing baseline profile file (somewhere in the middle)
* Observe that it throws an error and syntax highlighting also stops processing further

It might need an update on BNF rules for this?

**Comment by tikurahul** [comment]
Yes, i need to account for this in the BNF rules.
